apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-secrets
  namespace: devops-tools
spec:
  type: kv-v2
  mount: secret
  path: jenkins
  destination:
    name: jenkins-vault-secrets
    create: true
  refreshAfter: 30s
  vaultAuthRef: devops-auth