apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.applicationSet.name }}
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          {{- range .Values.applicationSet.apps }}
          - name: {{ .name }}
            namespace: {{ .namespace }}
            chart: {{ .chart }}
            version: {{ .version | quote }}
            disableAutoSync: {{ .disableAutoSync | default false | quote }}
          {{- end }}
  template:
    metadata:
      name: "{{`{{name}}`}}"
    spec:
      project: default
      sources:
        - repoURL: {{ .Values.applicationSet.chartsRepo }}
          chart: "{{`{{chart}}`}}"
          targetRevision: "{{`{{version}}`}}"
          helm:
            valueFiles:
              - $values/apps/{{`{{name}}`}}/values.yaml
        - repoURL: {{ .Values.applicationSet.repo }}
          targetRevision: {{ .Values.applicationSet.revision }}
          ref: values
        - repoURL: {{ .Values.applicationSet.repo }}
          targetRevision: {{ .Values.applicationSet.revision }}
          path: appconfig/{{`{{name}}`}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{namespace}}`}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    {{`{{- if eq .disableAutoSync "false"}}`}}
    spec:
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
    {{`{{- end}}`}}