apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-tools
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          {{- range .Values.applications }}
          - name: {{ .name }}
            chart: {{ .chart }}
            version: {{ .targetRevision }}
            values: |
{{ .values | indent 14 }}
          {{- end }}

  template:
    metadata:
      name: '{{`{{name}}`}}'
      namespace: argocd

    spec:
      project: default

      source:
        repoURL: https://priyanshu3103.github.io/helm-charts
        chart: '{{`{{chart}}`}}'
        targetRevision: '{{`{{version}}`}}'

        helm:
          values: |
{{`{{values}}` | indent 12 }}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{name}}`}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true