replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
  hosts:
    - host: jenkins.localhost
      paths:
        - path: /
          pathType: Prefix

agent:
  enabled: true
  image:
    repository: priyanshu30/jenkins-mysql
    tag: "tag-2"
  workingDir: "/home/jenkins/agent"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Optional but recommended
  args: "${computer.jnlpmac} ${computer.name}"
  # Keep same label as your pipelines
  podName: "jenkins-agent"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi