replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "false"
  hosts:
    - host: jenkins.localhost
      paths:
        - path: /
          pathType: Prefix

  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi