applications:
  - name: helm-argocd
    namespace: helm-argocd
    project: default
    repoURL: https://priyanshu3103.github.io/helm-charts   # Helm repo URL
    targetRevision: 0.1.0                                   # Chart version
    chart: helm-argocd                                      # Chart name
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: helm-argocd-dev
    namespace: helm-argocd-dev
    project: default
    destination: https://172.21.0.2:6443    # k3d dev-cluster
    repoURL: https://priyanshu3103.github.io/helm-charts
    targetRevision: 0.2.3
    chart: helm-argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true

  - name: nginx-ingress
    namespace: ingress-nginx
    project: default
    destination: https://172.21.0.2:6443
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx
    helmValues: |
      controller:
        service:
          type: NodePort
        hostPort:
          enabled: false
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true