applicationSet:
  name: devops-tools
  repo: https://github.com/priyanshu3103/helm-argocd.git
  revision: HEAD
  chartsRepo: https://priyanshu3103.github.io/helm-charts
  apps:
    - name: jenkins
      chartsRepo: http://chartmuseum.chartmuseum.svc.cluster.local:8080
      namespace: devops-tools
      chart: jenkins
      version: 0.3.16
      disableAutoSync: true
    - name: k8s-dashboard
      chartsRepo: http://chartmuseum.chartmuseum.svc.cluster.local:8080
      namespace: devops-tools
      chart: k8s-dashboard
      version: 0.1.36
      disableAutoSync: true
    - name: chartmuseum
      chartsRepo: https://chartmuseum.github.io/charts
      namespace: chartmuseum
      chart: chartmuseum
      version: 3.10.4
      disableAutoSync: true
    - name: github-runner
      chartsRepo: http://chartmuseum.chartmuseum.svc.cluster.local:8080
      namespace: devops-tools
      chart: github-runner
      version: 0.2.3
      disableAutoSync: "false"
    - name: vault
      chartsRepo: https://helm.releases.hashicorp.com
      namespace: vault
      chart: vault
      version: "0.28.1"
      disableAutoSync: "false"
    - name: vault-secrets-operator
      chartsRepo: https://helm.releases.hashicorp.com
      namespace: vault-secrets-operator-system
      chart: vault-secrets-operator
      version: "0.7.1"
      disableAutoSync: "false"
