applicationSet:
  name: devops-tools
  repo: https://github.com/priyanshu3103/helm-argocd.git
  revision: HEAD
  chartsRepo: https://priyanshu3103.github.io/helm-charts

  apps:
    - name: jenkins
      namespace: devops-tools
      chart: jenkins
      version: 0.2.40
      syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true