# In your chartmuseum app values
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: chartmuseum.localhost
      paths:
        - path: /
          pathType: Prefix