runner:
  githubUrl: "priyanshu3103/helm-charts"
  runnerName: "k8s-github-runner"
  labels: "k8s,self-hosted,linux"
  ephemeral: "true"
  replaceExistingRunner: "true"
  tokenSecretName: github-runner-secret
  tokenSecretKey: runner-token
env:
  - name: RUNNER_NAME
    value: k8s-github-runner
  - name: RUNNER_ORG
    value: priyanshu3103
  - name: EPHEMERAL
    value: "true"
  - name: REPLACE_EXISTING_RUNNER
    value: "true"
  - name: RUNNER_TOKEN
    valueFrom:
      secretKeyRef:
        name: github-runner-secret
        key: runner-token