runner:
  githubUrl: "https://github.com/priyanshu3103/helm-charts"
  runnerName: "k3d-runner"
  labels: "k3d,self-hosted,linux"
env:
  - name: RUNNER_NAME
    value: k3d-runner
  - name: RUNNER_ORG
    value: priyanshu3103
  - name: EPHEMERAL
    value: "true"
  - name: REPLACE_EXISTING_RUNNER
    value: "true"
  - name: RUNNER_TOKEN
    valueFrom:
      secretKeyRef:
        name: github-runner-secret
        key: runner-token