runner:
  githubUrl: "https://github.com/priyanshu3103/helm-charts"
  runnerName: "k3d-runner"
  runs-on:
  - self-hosted
  - linux
  - k3d
env:
  - name: RUNNER_NAME
    value: k3d-runner
  - name: RUNNER_ORG
    value: priyanshu3103