apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-app-config
  namespace: devops-tools
data:
  JENKINS_URL: "http://jenkins.devops-tools.svc.cluster.local:8080"
  JENKINS_HOME: "/opt/jenkins_home"
  JENKINS_INSTALL_PLUGINS: "git,workflow-aggregator,docker-plugin"
  JENKINS_ADMIN_USER: "admin"
